version: "3"

services:
  app:
    container_name: gc
    image: storage.zetxx.eu:5000/gc:latest
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ${HOME}/.goldencheetah/:/.goldencheetah/
      - /tmp/.X11-unix:/tmp/.X11-unix
    user: "1000:1000"